---
version: "2.0"

services:
  web:
    image: zjor/qr-share:94538ef
    expose:
      - port: 5000
        as: 80
        http_options:
          max_body_size: 26214400        
        accept:
          - qrshare.io
          - www.qrshare.io
        to:
          - global: true
    env:
      - PORT=5000
      - REGION=us-east-1
      - S3_API_KEY=<API_KEY>
      - S3_SECRET=<SECRET>
      - S3_ENDPOINT=https://s3.filebase.com

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    akash:
      attributes:
        host: nixaid
      pricing:
        web: 
          denom: uakt
          amount: 1000

deployment:
  web:
    akash:
      profile: web
      count: 1
